## numpy练习题

**1. Create a null vector of size 10**

In [1]:
import numpy as np
a1 = np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**2. Create a null vector of size 10 but the fifth value which is 1**

In [2]:
import numpy as np
a2 = np.zeros(10)
a2[4] = 1
a2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**3. Create a vector with values ranging from 10 to 49**

In [3]:
import numpy as np
a3 = np.arange(10, 50)
a3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**4. Create a 3x3 matrix with values ranging from 0 to 8**

In [4]:
import numpy as np
a4 = np.arange(9).reshape(3, 3)
a4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**5. Create a 10x10 array with random values and find the minimum and maximum values**

In [6]:
import numpy as np
a5 = np.random.random((10, 10))
n1 = a5.max()
n2 = a5.min()
print(a5)
print("max = ", n1)
print("min = ", n2)

[[0.28790329 0.79580433 0.25790196 0.27760941 0.44426813 0.89565727
  0.21634186 0.43257563 0.53755586 0.88293501]
 [0.64931138 0.39344683 0.7242187  0.46811889 0.31284247 0.01379243
  0.36226762 0.73388815 0.8293762  0.4090162 ]
 [0.47888994 0.07360742 0.87667349 0.10032413 0.72576904 0.54270286
  0.05003654 0.37393633 0.04822937 0.44161183]
 [0.91445165 0.63354136 0.05068053 0.21062187 0.59009316 0.05267523
  0.41146322 0.78486682 0.87716146 0.76146257]
 [0.49354177 0.95775875 0.03039422 0.54731146 0.29571837 0.15903826
  0.93139071 0.67694033 0.25426973 0.60334114]
 [0.84231818 0.09797382 0.79384666 0.32039696 0.55551834 0.30353322
  0.16936705 0.91965657 0.56195197 0.24036754]
 [0.30298718 0.96844071 0.17938258 0.3400997  0.65381871 0.48398036
  0.59422355 0.27116645 0.15745225 0.72433024]
 [0.9855447  0.31224796 0.58588737 0.5336093  0.32373209 0.95075695
  0.23485521 0.04729497 0.34341705 0.03099825]
 [0.84435164 0.39387855 0.69342038 0.77700778 0.22530733 0.20155875
  0.48467907

**6. Create a 2d array with 1 on the border and 0 inside**

In [7]:
import numpy as np
def func(n):
    arr = np.zeros([n] * 2)
    arr[[0, -1], :] = 1
    arr[:, [0, -1]] = 1
    return arr
num = int(input("enter a number:"))
a6 = func(num)
a6

enter a number:5


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**7. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [9]:
import numpy as np
a7 = np.arange(15).reshape(5, 3)
a8 = np.arange(6).reshape(3, 2)
a9 = np.dot(a7, a8)
print(a7)
print(a8)
print(a9)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
